<script setup lang="ts">
import { ref } from 'vue'
const props = defineProps<{ document: { student: string; requirement: string; department: string; submitted: string; fileName?: string } }>()
const emit = defineEmits<{ (event: 'close'): void; (event: 'reviewed', status: 'Approved' | 'Rejected', remarks: string): void }>()
const remarks = ref('')

function review(status: 'Approved' | 'Rejected') {
	if (status === 'Rejected' && !remarks.value.trim()) return
	emit('reviewed', status, remarks.value.trim())
}
</script>
<template><div class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" @click.self="emit('close')"><section class="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl" role="dialog" aria-modal="true"><div class="flex justify-between"><h2 class="text-xl font-bold">Review Document</h2><button class="text-2xl text-slate-400" aria-label="Close" @click="emit('close')">&times;</button></div><dl class="mt-5 space-y-3 text-sm"><div><dt class="text-slate-500">Student</dt><dd class="font-semibold">{{ props.document.student }}</dd></div><div><dt class="text-slate-500">Requirement</dt><dd class="font-semibold">{{ props.document.requirement }}</dd></div><div><dt class="text-slate-500">Department</dt><dd class="font-semibold">{{ props.document.department }}</dd></div><div><dt class="text-slate-500">Submitted</dt><dd class="font-semibold">{{ props.document.submitted }}</dd></div><div v-if="props.document.fileName"><dt class="text-slate-500">Uploaded file</dt><dd class="font-semibold break-all">{{ props.document.fileName }}</dd></div></dl><label class="mt-5 block text-sm font-semibold text-slate-700" for="review-remarks">Review comment<span class="text-red-500"> *</span></label><textarea id="review-remarks" v-model="remarks" rows="3" placeholder="Explain the decision, especially if rejecting" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"></textarea><div class="mt-6 flex justify-end gap-3"><button class="rounded-lg border border-red-200 px-4 py-2 text-sm font-semibold text-red-600 disabled:opacity-50" :disabled="!remarks.trim()" @click="review('Rejected')">Reject</button><button class="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white" @click="review('Approved')">Approve</button></div></section></div></template>